[project]
name = "idli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg-pool>=3.2.8",
    "psycopg[binary]>=3.2.13",
]

[dependency-groups]
dev = [
    "python-lsp-server>=1.13.2",
]
